### ISSUE TITLE
doesn't detect the crew 2

### ISSUE THREAD

**Issue by wandomity** [James-LG/AutoCursorLock#21]
i have a problem with it not detecting the crew 2 on the add processes, even when i press refresh multiple times

![image](https://github.com/user-attachments/assets/5bde320f-13d5-4d13-b046-559b57425d09)

**Comment by James-LG** [comment]
I need to see the logs. Open your game, then open the file `%appdata%\AutoCursorLock\log.txt` and paste some of the most recent lines from the log file in a comment here.

I'm looking for logs that say `[ERR]` or logs that say something to do with 'the crew'.

My guess is that AutoCursorLock is getting permission errors when inspecting the window.

**Comment by KuritasKRT** [comment]
For what it's worth, I have the same problem with Space Marine 2:

`[ERR] Failed to get process list item for process: Warhammer 40000 Space Marine 2 - Retail
System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.NtProcessManager.EnumProcessModulesUntilSuccess(SafeProcessHandle processHandle, IntPtr[] modules, Int32 size, Int32& needed, Int32 filterFlag)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at AutoCursorLock.App.Views.MainWindow.RefreshButton_Click(Object sender, RoutedEventArgs e) in D:\code\AutoCursorLock\src\AutoCursorLock.App\Views\MainWindow.xaml.cs:line 305`

**Comment by James-LG** [comment]
Interesting, could be a permission issue getting the icon or the executable path. I can try just giving those programs blank icons and see if windows at least lets AutoCursorLock detect when the window is in focus without permissions errors.
